github/workflows: update GitHub-hosted runner Ubuntu image 20.04 -> 22.04
Explicit installation of chrpath is now required:

  ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
    chrpath

Signed-off-by: Bastian Krause <bst@pengutronix.de>